global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: galaxyserve
    metrics_path: /metrics
    static_configs:
      - targets: ["galaxyserve:8000"]
        labels:
          service: galaxyserve

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
